name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, AWS_SQS_URL
          script: |
            echo "AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:+set}"
            echo "AWS_REGION: $AWS_REGION"
            cd sqs-polling
            git pull origin main
            sudo docker build -t sqs-poller .
            sudo docker stop $(sudo docker ps -q --filter ancestor=sqs-poller) || true
            sudo docker rm $(sudo docker ps -aq --filter ancestor=sqs-poller) || true
            sudo docker run -d --restart unless-stopped \
              -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
              -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
              -e AWS_REGION=$AWS_REGION \
              -e AWS_SQS_URL=$AWS_SQS_URL \
              sqs-poller
