name: Deploy SQS Processor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        run: |
          docker build -t sqs-processor .
          docker tag sqs-processor:latest 793130699528.dkr.ecr.us-east-1.amazonaws.com/sqs-processor:latest
          docker push 793130699528.dkr.ecr.us-east-1.amazonaws.com/sqs-processor:latest
          
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION
          script: |
            echo "Logging into ECR on EC2 instance"
            aws ecr get-login-password --region $AWS_REGION | sudo docker login --username AWS --password-stdin 793130699528.dkr.ecr.us-east-1.amazonaws.com

            echo "Pulling the latest image from ECR"
            sudo docker pull 793130699528.dkr.ecr.us-east-1.amazonaws.com/sqs-processor:latest

            echo "Stopping existing container if any"
            sudo docker stop $(sudo docker ps -q --filter ancestor=sqs-processor) || true
            sudo docker rm $(sudo docker ps -aq --filter ancestor=sqs-processor) || true

            echo "Running the new container"
            sudo docker run -d --restart unless-stopped \
              -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
              -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
              -e AWS_REGION=$AWS_REGION \
              sqs-processor      